stages:
  - stage: Infrastructure
    jobs:
      - job: 'CreateAzureInfra'
        displayName: 'Create Azure Infrastructure'
        pool: ''                                                # PROVIDE A BUILD IMAGE
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Create infrastructure'
            condition: succeeded()
            inputs:
              azureSubscription: ''                             # PROVIDE AN AZURE SUBSCRIPTION - defined in Azure DevOps
              ScriptLocation: 'inlineScript'
              scriptType: 'pscore'
              inlineScript: |
                az deployment sub create --location 'westeurope' `
                  --template-file $(Build.SourcesDirectory)/pipeline/template/main.bicep `
                  --parameters $(Build.SourcesDirectory)/pipeline/template/main-parameters.json
  - stage: Build
    jobs:
      - job: 'BuildApp'
        displayName: 'Build the application'
        pool: ''                                                # PROVIDE A BUILD IMAGE
        steps:
          - checkout: self
          - task: Maven@3
            displayName: 'Maven build'
            condition: succeeded()
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx512m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              goals: 'package'
          - task: Docker@2
            displayName: 'Push an image to Azure Container Registry'
            inputs:
              command: push
              repository: 'vehicles'
              dockerfile: $(system.defaultworkingdirectory)/target/Dockerfile
              containerRegistry: ''                   # PROVIDE A SERVICE CONNECTION - defined in Azure DevOps
              tags: 'latest'
